# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_base_bar(object):
    def setupUi(self, base_bar):
        base_bar.setObjectName("base_bar")
        base_bar.resize(591, 100)
        self.horizontalLayout = QtWidgets.QHBoxLayout(base_bar)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_logo = QtWidgets.QPushButton(base_bar)
        self.app_logo.setText("")
        self.app_logo.setObjectName("app_logo")
        self.horizontalLayout.addWidget(self.app_logo)
        self.app_name = QtWidgets.QPushButton(base_bar)
        self.app_name.setText("")
        self.app_name.setObjectName("app_name")
        self.horizontalLayout.addWidget(self.app_name)
        spacerItem = QtWidgets.QSpacerItem(408, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bar_btn_min = QtWidgets.QPushButton(base_bar)
        self.bar_btn_min.setText("")
        self.bar_btn_min.setObjectName("bar_btn_min")
        self.horizontalLayout.addWidget(self.bar_btn_min)
        self.bar_btn_normal = QtWidgets.QPushButton(base_bar)
        self.bar_btn_normal.setText("")
        self.bar_btn_normal.setObjectName("bar_btn_normal")
        self.horizontalLayout.addWidget(self.bar_btn_normal)
        self.bar_btn_close = QtWidgets.QPushButton(base_bar)
        self.bar_btn_close.setText("")
        self.bar_btn_close.setObjectName("bar_btn_close")
        self.horizontalLayout.addWidget(self.bar_btn_close)

        self.retranslateUi(base_bar)
        QtCore.QMetaObject.connectSlotsByName(base_bar)

    def retranslateUi(self, base_bar):
        _translate = QtCore.QCoreApplication.translate
        base_bar.setWindowTitle(_translate("base_bar", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    base_bar = QtWidgets.QWidget()
    ui = Ui_base_bar()
    ui.setupUi(base_bar)
    base_bar.show()
    sys.exit(app.exec_())
